import type { BibleBook } from '../services/BibleService';

export const BIBLE_BOOKS: BibleBook[] = [
    // Old Testament
    { id: 'GEN', name: 'Genesis', order: 1, chapterCount: 50 },
    { id: 'EXO', name: 'Exodus', order: 2, chapterCount: 40 },
    { id: 'LEV', name: 'Leviticus', order: 3, chapterCount: 27 },
    { id: 'NUM', name: 'Numbers', order: 4, chapterCount: 36 },
    { id: 'DEU', name: 'Deuteronomy', order: 5, chapterCount: 34 },
    { id: 'JOS', name: 'Joshua', order: 6, chapterCount: 24 },
    { id: 'JDG', name: 'Judges', order: 7, chapterCount: 21 },
    { id: 'RUT', name: 'Ruth', order: 8, chapterCount: 4 },
    { id: '1SA', name: '1 Samuel', order: 9, chapterCount: 31 },
    { id: '2SA', name: '2 Samuel', order: 10, chapterCount: 24 },
    { id: '1KI', name: '1 Kings', order: 11, chapterCount: 22 },
    { id: '2KI', name: '2 Kings', order: 12, chapterCount: 25 },
    { id: '1CH', name: '1 Chronicles', order: 13, chapterCount: 29 },
    { id: '2CH', name: '2 Chronicles', order: 14, chapterCount: 36 },
    { id: 'EZR', name: 'Ezra', order: 15, chapterCount: 10 },
    { id: 'NEH', name: 'Nehemiah', order: 16, chapterCount: 13 },
    { id: 'EST', name: 'Esther', order: 17, chapterCount: 10 },
    { id: 'JOB', name: 'Job', order: 18, chapterCount: 42 },
    { id: 'PSA', name: 'Psalms', order: 19, chapterCount: 150 },
    { id: 'PRO', name: 'Proverbs', order: 20, chapterCount: 31 },
    { id: 'ECC', name: 'Ecclesiastes', order: 21, chapterCount: 12 },
    { id: 'SNG', name: 'Song of Solomon', order: 22, chapterCount: 8 },
    { id: 'ISA', name: 'Isaiah', order: 23, chapterCount: 66 },
    { id: 'JER', name: 'Jeremiah', order: 24, chapterCount: 52 },
    { id: 'LAM', name: 'Lamentations', order: 25, chapterCount: 5 },
    { id: 'EZK', name: 'Ezekiel', order: 26, chapterCount: 48 },
    { id: 'DAN', name: 'Daniel', order: 27, chapterCount: 12 },
    { id: 'HOS', name: 'Hosea', order: 28, chapterCount: 14 },
    { id: 'JOL', name: 'Joel', order: 29, chapterCount: 3 },
    { id: 'AMO', name: 'Amos', order: 30, chapterCount: 9 },
    { id: 'OBA', name: 'Obadiah', order: 31, chapterCount: 1 },
    { id: 'JON', name: 'Jonah', order: 32, chapterCount: 4 },
    { id: 'MIC', name: 'Micah', order: 33, chapterCount: 7 },
    { id: 'NAM', name: 'Nahum', order: 34, chapterCount: 3 },
    { id: 'HAB', name: 'Habakkuk', order: 35, chapterCount: 3 },
    { id: 'ZEP', name: 'Zephaniah', order: 36, chapterCount: 3 },
    { id: 'HAG', name: 'Haggai', order: 37, chapterCount: 2 },
    { id: 'ZEC', name: 'Zechariah', order: 38, chapterCount: 14 },
    { id: 'MAL', name: 'Malachi', order: 39, chapterCount: 4 },
    // New Testament
    { id: 'MAT', name: 'Matthew', order: 40, chapterCount: 28 },
    { id: 'MRK', name: 'Mark', order: 41, chapterCount: 16 },
    { id: 'LUK', name: 'Luke', order: 42, chapterCount: 24 },
    { id: 'JHN', name: 'John', order: 43, chapterCount: 21 },
    { id: 'ACT', name: 'Acts', order: 44, chapterCount: 28 },
    { id: 'ROM', name: 'Romans', order: 45, chapterCount: 16 },
    { id: '1CO', name: '1 Corinthians', order: 46, chapterCount: 16 },
    { id: '2CO', name: '2 Corinthians', order: 47, chapterCount: 13 },
    { id: 'GAL', name: 'Galatians', order: 48, chapterCount: 6 },
    { id: 'EPH', name: 'Ephesians', order: 49, chapterCount: 6 },
    { id: 'PHP', name: 'Philippians', order: 50, chapterCount: 4 },
    { id: 'COL', name: 'Colossians', order: 51, chapterCount: 4 },
    { id: '1TH', name: '1 Thessalonians', order: 52, chapterCount: 5 },
    { id: '2TH', name: '2 Thessalonians', order: 53, chapterCount: 3 },
    { id: '1TI', name: '1 Timothy', order: 54, chapterCount: 6 },
    { id: '2TI', name: '2 Timothy', order: 55, chapterCount: 4 },
    { id: 'TIT', name: 'Titus', order: 56, chapterCount: 3 },
    { id: 'PHM', name: 'Philemon', order: 57, chapterCount: 1 },
    { id: 'HEB', name: 'Hebrews', order: 58, chapterCount: 13 },
    { id: 'JAS', name: 'James', order: 59, chapterCount: 5 },
    { id: '1PE', name: '1 Peter', order: 60, chapterCount: 5 },
    { id: '2PE', name: '2 Peter', order: 61, chapterCount: 3 },
    { id: '1JN', name: '1 John', order: 62, chapterCount: 5 },
    { id: '2JN', name: '2 John', order: 63, chapterCount: 1 },
    { id: '3JN', name: '3 John', order: 64, chapterCount: 1 },
    { id: 'JUD', name: 'Jude', order: 65, chapterCount: 1 },
    { id: 'REV', name: 'Revelation', order: 66, chapterCount: 22 },
];
